apiVersion: v1
kind: Namespace
metadata:
  name: nicolasb
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: quelpokenicolasb
  namespace: nicolasb
spec:
  parentRefs:
  - kind: Gateway
    name: nicolasexternal-http-gateway
    namespace: infra
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /quelpoke.copy-paste.pro/nicolasb
    backendRefs:
    - name: quelpokenicolasb
      port: 8080

---
apiVersion: v1
kind: Service
metadata:
    name: quelpokenicolasb
    namespace: nicolasb
spec:
  selector:
    app.kubernetes.io/name: quelpokenicolasb
  ports:
    - name: name-of-service-port
      protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quelpokenicolasb
  namespace: nicolasb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quelpokenicolasb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: quelpokenicolasb
    spec:
      containers:
      - name: quelpokenicolasb
        image: europe-west9-docker.pkg.dev/cs-poc-hpzdycpiqjyvinhrczvlwcn/student-nicolasb/quelpoke:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"