---
# Source: quelpokenicolasb/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: nicolasb
---
# Source: quelpokenicolasb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: quelpokenicolasb
  namespace: nicolasb
spec:
  selector:
    app.kubernetes.io/name: quelpokenicolasb
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
# Source: quelpokenicolasb/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quelpokenicolasb
  namespace: nicolasb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quelpokenicolasb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: quelpokenicolasb
    spec:
      containers:
        - name: quelpokenicolasb
          image: "your-docker-repo/quelpokenicolasb:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
---
# Source: quelpokenicolasb/templates/httproute.yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: quelpokenicolasb
  namespace: nicolasb
spec:
  parentRefs:
    - kind: Gateway
      name: external-http-gateway
      namespace: infra
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /nicolasb
      backendRefs:
        - name: quelpokenicolasb
          port: 8080
