name: Deploy to Google Cloud VM

on:
  push:
    branches: [main] 

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ vars.ARTIFACT_LOCATION }}-docker.pkg.dev -q

      - name: Build image
        env:
          IMAGE: ${{ vars.ARTIFACT_LOCATION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.ARTIFACT_REPO_ID }}/quelpoke
        run: |
          docker build -t "${IMAGE}:${GITHUB_SHA}" -t "${IMAGE}:latest" .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Push Docker image
        run: |
          docker push "${IMAGE}:${GITHUB_SHA}"
          docker push "${IMAGE}:latest"

      # --- Récupère les credentials du cluster (GKE) ---
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ vars.GKE_CLUSTER }}
          location: ${{ vars.GKE_LOCATION }}   # zone ou région (ex: europe-west9)
          project_id: ${{ vars.GCP_PROJECT_ID }}

      # --- Déploiement ---
      - name: Apply manifests (create/update)
        run: |
          kubectl apply -f config.yaml

      - name: Set image to current SHA (rollout)
        run: |
          kubectl -n nicolasb set image deployment/quelpokenicolasb quelpokenicolasb="${IMAGE}:${GITHUB_SHA}"
          kubectl -n nicolasb rollout status deployment/quelpokenicolasb --timeout=120s